# ============================================ #
#      Настройки плагина StalkerEmission v1.4    #
# ============================================ #

emission:
  interval: 30
  warning_duration: 60
  duration: 120

  # --- НОВЫЙ БЛОК: Прогрессивный урон ---
  # Урон будет плавно увеличиваться от минимального к максимальному за время выброса.
  # 1.0 = половина сердечка.
  progressive_damage:
    min: 0.5  # Урон в самом начале выброса (за секунду).
    max: 2.0  # Урон на пике выброса (в самом конце).

  # --- Эффекты зелий ---
  # Теперь это МАКСИМАЛЬНЫЙ уровень, который будет достигнут к концу выброса.
  # Плагин будет плавно повышать уровень эффектов с 0 до указанного значения.
  # Пример для SLOW: 1. Будет уровень 0, потом станет 1.
  # Пример для WEAKNESS: 2. Будет 0 -> 1 -> 2.
  effects:
    POISON: 0      # Этот эффект будет постоянного 0-го уровня
    BLINDNESS: 1   # Этот эффект начнется с 0 и дойдет до 1-го уровня
    SLOW: 2        # Начнется с 0, станет 1, а на пике будет 2-го уровня

# Настройки укрытия (без изменений)
shelter:
  max_check_height: 256

# --- НОВЫЙ БЛОК: Прогрессивные визуальные эффекты ---
visuals:
  # Шанс удара молнии также будет расти со временем.
  progressive_lightning:
    min_chance: 5   # Шанс в начале (в %)
    max_chance: 20  # Шанс в конце (в %)

  # Шанс взрыва-аномалии.
  progressive_explosion:
    min_chance: 2
    max_chance: 10

# Сообщения (без изменений)
messages:
  warning_title: "&4&lВНИМАНИЕ!"
  warning_subtitle: "&cПриближается выброс! Ищите укрытие!"
  emission_start_title: "&4&lВЫБРОС!"
  emission_start_subtitle: "&cНадеюсь, ты в укрытии..."
  emission_end_title: "&aВыброс окончен"
  emission_end_subtitle: "&eМожно выходить из укрытий."
